name: Build and Push to ECR

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: 381492290017.dkr.ecr.us-east-1.amazonaws.com/wr

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::381492290017:role/ECRAccessGithubRole
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      run: |
        docker build -t $ECR_REPOSITORY:latest .
        docker push $ECR_REPOSITORY:latest

#									--build-arg SECRET_KEY=${{ env.SECRET_KEY }} \
#									--build-arg DB_NAME=${{ env.DB_NAME }} \
#									--build-arg DB_USER=${{ env.DB_USER }} \
#									--build-arg DB_PASSWORD=${{ env.DB_PASSWORD }} \
#									--build-arg DB_HOST=${{ env.DB_HOST }} \
#									--build-arg DB_PORT=${{ env.DB_PORT }} \
#									--build-arg REDIS_HOST=${{ env.REDIS_HOST }} \